name: pretty_tostring
description: Generates structured toString() implementations for annotated classes.
version: 0.0.6
environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.3
  source_gen: ^4.1.1

dev_dependencies:
  test: ^1.28.0
  build_runner: ^2.10.4
  build_test: ^3.5.4
  source_gen_test: ^1.3.2
  flutter_lints: ^6.0.0
